package it.keypartner.fma_play;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DetailsDTO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String code;

   public DetailsDTO()
   {
   }

   public java.lang.String getCode()
   {
      return this.code;
   }

   public void setCode(java.lang.String code)
   {
      this.code = code;
   }

   public DetailsDTO(java.lang.String code)
   {
      this.code = code;
   }

}