package it.keypartner.fma_play;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NotificationDTO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String message;

   public NotificationDTO()
   {
   }

   public java.lang.String getMessage()
   {
      return this.message;
   }

   public void setMessage(java.lang.String message)
   {
      this.message = message;
   }

   public NotificationDTO(java.lang.String message)
   {
      this.message = message;
   }

}