package it.keypartner.fma_play;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NotificationDTO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String message;

   private it.keypartner.fma_play.DetailsDTO detail;

   public NotificationDTO()
   {
   }

   public java.lang.String getMessage()
   {
      return this.message;
   }

   public void setMessage(java.lang.String message)
   {
      this.message = message;
   }

   public it.keypartner.fma_play.DetailsDTO getDetail()
   {
      return this.detail;
   }

   public void setDetail(it.keypartner.fma_play.DetailsDTO detail)
   {
      this.detail = detail;
   }

   public NotificationDTO(java.lang.String message,
         it.keypartner.fma_play.DetailsDTO detail)
   {
      this.message = message;
      this.detail = detail;
   }

}