package it.keypartner.fma_play;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NotificationDTO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public NotificationDTO() {
    }

}