package keypartner.form_modeling;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MyModel implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MyModel() {
    }

}